# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).

    The version of the OpenAPI document: 0.1.0
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.models.supported_upgrade import SupportedUpgrade

class TestSupportedUpgrade(unittest.TestCase):
    """SupportedUpgrade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedUpgrade(self):
        """Test SupportedUpgrade"""
        # inst = SupportedUpgrade()

if __name__ == '__main__':
    unittest.main()
