# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).

    The version of the OpenAPI document: 0.1.0
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.api.building_profiler_api import BuildingProfilerApi


class TestBuildingProfilerApi(unittest.TestCase):
    """BuildingProfilerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuildingProfilerApi()

    def tearDown(self) -> None:
        pass

    def test_get_home_profile(self) -> None:
        """Test case for get_home_profile

        Get Home Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
