# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).

    The version of the OpenAPI document: 0.1.0
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.models.metric_statistics import MetricStatistics

class TestMetricStatistics(unittest.TestCase):
    """MetricStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricStatistics:
        """Test MetricStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricStatistics`
        """
        model = MetricStatistics()
        if include_optional:
            return MetricStatistics(
                mean = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                median = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                percentile_20 = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                percentile_80 = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', )
            )
        else:
            return MetricStatistics(
                mean = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                median = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                percentile_20 = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
                percentile_80 = rewiringamerica_rem.models.quantity.Quantity(
                    value = 1.337, 
                    units = '', ),
        )
        """

    def testMetricStatistics(self):
        """Test MetricStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
