# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).

    The version of the OpenAPI document: 0.1.0
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.api.residential_electrification_model_api import ResidentialElectrificationModelApi


class TestResidentialElectrificationModelApi(unittest.TestCase):
    """ResidentialElectrificationModelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResidentialElectrificationModelApi()

    def tearDown(self) -> None:
        pass

    def test_get_by_address(self) -> None:
        """Test case for get_by_address

        Get By Address
        """
        pass

    def test_get_by_profile(self) -> None:
        """Test case for get_by_profile

        Get By Profile
        """
        pass

    def test_get_impl_version(self) -> None:
        """Test case for get_impl_version

        Get Impl Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
