# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).

    The version of the OpenAPI document: 0.1.0
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SupportedUpgrade(str, Enum):
    """
    Upgrades accepted by the REM API.
    """

    """
    allowed enum values
    """
    BASIC_ENCLOSURE = 'basic_enclosure'
    MIN_EFF_HP_ELEC_BACKUP = 'min_eff_hp_elec_backup'
    HIGH_EFF_HP_ELEC_BACKUP = 'high_eff_hp_elec_backup'
    WHOLE_HOME_ELECTRIC_MAX_EFF_BASIC_ENCLOSURE = 'whole_home_electric_max_eff_basic_enclosure'
    MED_EFF_HP_HERS_SIZING_NO_SETBACK = 'med_eff_hp_hers_sizing_no_setback'
    MED_EFF_HP_HERS_SIZING_NO_SETBACK_BASIC_ENCLOSURE = 'med_eff_hp_hers_sizing_no_setback_basic_enclosure'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportedUpgrade from a JSON string"""
        return cls(json.loads(json_str))


